name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: codecov/codecov-action@v1

  artifact-build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: Set up rust nightly
        run: rustup override set nightly
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: Linux binary
          path: target/release/dpm
